### ISSUE TITLE
Evaluate Switching to Traefik

### ISSUE THREAD

**Issue by phikai** [phikai/htpc-docker-standup#3]
Could be interesting to move to Traefik for a few reasons:

1. Try some new things!
2. Looks like it's possible to support Plex w/ SSL.

Some implementation examples:
- https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/#Traefik_vs_Nginx_Proxy

Traefik: https://traefik.io/

**Comment by welcoMattic** [comment]
Here's my version of the docker-compose.yml file with Traefik:

```yaml
version: '2'

services:
    router:
        image: traefik:tetedemoine-alpine
        container_name: traefik
        restart: always
        network_mode: bridge
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config/traefik:/etc/traefik
            - ./log/traefik:/var/log/traefik
        labels:
            - "traefik.backend=router"
            - "traefik.port=8080"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:router.${DOMAIN}"

    plex:
        container_name: plex
        image: plexinc/pms-docker:${PMSTAG}
        restart: unless-stopped
        network_mode: bridge
        ports:
            - '${IP_ADDRESS}:32400:32400/tcp'
            - '${IP_ADDRESS}:3005:3005/tcp'
            - '${IP_ADDRESS}:8324:8324/tcp'
            - '${IP_ADDRESS}:32469:32469/tcp'
            - '${IP_ADDRESS}:1900:1900/udp'
            - '${IP_ADDRESS}:32410:32410/udp'
            - '${IP_ADDRESS}:32412:32412/udp'
            - '${IP_ADDRESS}:32413:32413/udp'
            - '${IP_ADDRESS}:32414:32414/udp'
        environment:
            - PLEX_CLAIM=${PMSTOKEN}
            - ADVERTISE_IP=http://${IP_ADDRESS}:32400/
            - PLEX_UID=${PUID}
            - PLEX_GID=${PGID}
        hostname: ${HOSTNAME}
        volumes:
            - './plex:/config'
            - './plex/transcode:/transcode'
            - '/home/${LOCALUSER}/media/Media/Media/Movies:/data/movies'
            - '/home/${LOCALUSER}/media/Media/Media/TVShows:/data/tvshows'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        labels:
            - "traefik.backend=plex"
            - "traefik.port=32400"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:plex.${DOMAIN}"

    rtorrent:
        image: vaeyo/rtorrent
        container_name: rtorrent
        restart: always
        network_mode: bridge
        volumes:
            - '/home/${LOCALUSER}/media/Media/Torrents:/downloads'
            - './rtorrent/config:/config'
            - './rtorrent/rutorrent/themes/MaterialDesign:/usr/share/webapps/rutorrent/plugins/theme/themes/MaterialDesign'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        labels:
            - "traefik.rutorrent.backend=rtorrent-rutorrent"
            - "traefik.rutorrent.port=80"
            - "traefik.rutorrent.frontend.rule=Host:rutorrent.${
            - "traefik.flood.backend=rtorrent-flood"
            - "traefik.flood.port=3000"
            - "traefik.flood.frontend.rule=Host:flood.${DOMAIN}"
            - "traefik.frontend.entryPoints=https"

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        restart: always
        network_mode: bridge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VIRTUAL_HOST=sonarr.${DOMAIN}
            - LETSENCRYPT_HOST=sonarr.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - './sonarr:/config'
            - '/home/${LOCALUSER}/media/Media/Torrents/Completed:/data/Completed'
            - '/home/${LOCALUSER}/media/Media/Media/TVShows:/tv'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        labels:
            - "traefik.backend=sonarr"
            - "traefik.port=8989"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:sonarr.${DOMAIN}"

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        restart: always
        network_mode: bridge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VIRTUAL_HOST=radarr.${DOMAIN}
            - LETSENCRYPT_HOST=radarr.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - './radarr:/config'
            - '/home/${LOCALUSER}/media/Media/Torrents/Completed:/data/Completed'
            - '/home/${LOCALUSER}/media/Media/Media/Movies:/movies'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        labels:
            - "traefik.backend=radarr"
            - "traefik.port=7878"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:radarr.${DOMAIN}"

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        restart: always
        network_mode: bridge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VIRTUAL_HOST=jackett.${DOMAIN}
            - LETSENCRYPT_HOST=jackett.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - './jackett:/config'
            - '/home/${LOCALUSER}/media/Media/Torrents/Completed:/downloads'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        labels:
            - "traefik.backend=jackett"
            - "traefik.port=9117"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:jackett.${DOMAIN}"

    plexpy:
        image: linuxserver/tautulli
        container_name: plexpy
        restart: always
        network_mode: bridge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VIRTUAL_HOST=plexpy.${DOMAIN}
            - LETSENCRYPT_HOST=plexpy.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - './plexpy:/config'
            - './plex/Library/Application Support/Plex Media Server/Logs:/logs:ro'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        depends_on:
            - plex
        labels:
            - "traefik.backend=plexpy"
            - "traefik.port=8181"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:plexpy.${DOMAIN}"

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        restart: always
        network_mode: bridge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VIRTUAL_HOST=request.${DOMAIN}
            - LETSENCRYPT_HOST=request.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - './ombi:/config'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        labels:
            - "traefik.backend=ombi"
            - "traefik.port=3579"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:ombi.${DOMAIN}"

    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: always
        network_mode: bridge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VIRTUAL_HOST=portainer.${DOMAIN}
            - LETSENCRYPT_HOST=portainer.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - './portainer:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        labels:
            - "traefik.backend=portainer"
            - "traefik.port=9000"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:portainer.${DOMAIN}"

    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        restart: always
        network_mode: bridge
        environment:
            - TZ=${TZ}
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${SMTP_FROM}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASS}
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/ssl/certs:/etc/ssl/certs'
        command: portainer --schedule @midnight --cleanup

    netdata:
        image: titpetric/netdata
        container_name: netdata
        restart: always
        network_mode: bridge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VIRTUAL_HOST=netdata.${DOMAIN}
            - LETSENCRYPT_HOST=netdata.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - '/proc:/host/proc:ro'
            - '/sys:/host/sys:ro'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
            - '/var/run/docker.sock:/var/run/docker.sock'
        labels:
            - "traefik.backend=netdata"
            - "traefik.port=19999"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:netdata.${DOMAIN}"

    duplicati:
        image: linuxserver/duplicati
        container_name: duplicati
        restart: always
        network_mode: bridge
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - VIRTUAL_HOST=duplicati.${DOMAIN}
            - LETSENCRYPT_HOST=duplicati.${DOMAIN}
            - LETSENCRYPT_EMAIL=${EMAIL}
        volumes:
            - './duplicati:/config'
            - '/home/${LOCALUSER}/media/Media/Media:/media'
            - '/usr/share/zoneinfo/Europe/Paris:/etc/localtime:ro'
        labels:
            - "traefik.backend=duplicati"
            - "traefik.port=8200"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:duplicati.${DOMAIN}"
```

If it could help you ;)
